site_name: Proteus
site_url: https://software.llnl.gov/proteus/

nav:
  - Home: index.md
  - User's guide:
      - Installation: user/install.md
      - Build System Integration: user/integration.md
      - User Interface:
          - Overview: user/interface.md
          - Code Annotations: user/annotations.md
          - Python Bindings: user/python-bindings.md
          - C++ Frontend API: user/cpp-frontend.md
          - LLVM IR Frontend API: user/llvmir-frontend.md
          - MLIR Frontend API: user/mlir-frontend.md
          - DSL API: user/dsl.md
      - Runtime Configuration: user/config.md
      - Resources : user/resources.md
  - Developer's manual:
    - Concepts: dev/concepts.md
    - Proteus Internals:
      - Overview: dev/proteus-internals.md
      - Optimization Pipeline: dev/optimization-pipeline.md
    - Python Wheel Build: dev/python-wheel.md
    - Detecting CUDA Toolchain: dev/runtime-cuda-toolchain.md
    - Detecting HIP Assets: dev/runtime-hip-toolchain.md
    - Creating a PR: dev/pr.md
    - API Reference: dev/api.md
repo_url: https://github.com/LLNL/proteus
theme:
  name: material
  features:
    - toc.integrate
  logo: assets/proteus-logo.png
  favicon: assets/proteus-logo.png
  palette:
    scheme: default
    primary: light blue
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - mike:
      alias_type: redirect
      canonical_version: latest
extra:
  version:
    provider: mike
    default: latest
    alias: true
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2024 - 2026 Lawrence Livermore National Security, LLC and Proteus project contributors.
